services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    networks:
      - container-stack-network

networks:
  container-stack-network:
    external: true
    name: container-stack-network
