version: "3.9"
services:
  mysql8:
    container_name: "mysql-8-service"
    image: mysql:8.0
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT_MYSQL}:3306"
    volumes:
      - mysql8-db-data:/var/lib/mysql

  postgres:
    container_name: "postgres-service"
    image: postgres:latest
    restart: always
    tty: true
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_POSTGRES}:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

  mssqlserver:
    container_name: "mssqlserver-service"
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    tty: true
    platform: linux/x86_64
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT_SQLSERVER}:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  mongodb:
    container_name: "mongodb-service"
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    tty: true
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT_MONGODB}:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mysql8-db-data:
    driver: local
  postgres-db-data:
    driver: local
  sqlserver-data:
    driver: local
  mongodb-data:
    driver: local
